name: FtpAnimePlayer-tvOS
options:
  bundleIdPrefix: com.ftpanimeplayer
  deploymentTarget:
    tvOS: "16.0"
targets:
  FtpAnimePlayer-tvOS:
    type: application
    platform: tvOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ftpanimeplayer.tvOS
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: "YES"
